### ISSUE TITLE
Unable to load sessions from file

### ISSUE THREAD

**Issue by RatkoJ** [BobLd/lean-monitor-2#2]
I am running Lean locally through Docker (LEAN CLI actually). The simple test backtest is generating two json files:
1. 1732096832.json
2. 1732096832-order-events.json

I cannot even open the first one in the lean-monitor GUI because the Open button stays grayed out.
And when I open the second one, it throws an exception on JSON deserialization:

`
"Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'QuantConnect.Packets.BacktestResult' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\nPath '', line 1, position 1."	string
`

Which file am I even supposed to be able to open with the lean-monitor? And how? Thanks!

Setup:
- macOS
- latest Lean from GitHub (13059)
- latest lean-monitor from GitHub

**Comment by BobLd** [comment]
Feel free to reopen this issue if you still have the problem
